"""init — scaffold a docs ecosystem from zero, optimized for solo devs.

Detects the project (Python / Node / Rust / Go / generic), generates a
minimal doc-plan based on the chosen preset, and runs `sync` to produce
the registry, the GitHub Action, and the audit log.

Presets:
    minimal   — README, ARCHITECTURE, GOTCHAS (default for hobby projects)
    standard  — adds CONTRIBUTING, ENVIRONMENT, RUNBOOK
    full      — every doc type in doc-types.yaml

Usage:
    docs-gen init
    docs-gen init --preset standard --scaffold
    docs-gen init --interactive --force
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    import sys
    print("❌ pyyaml required. Install: pip install pyyaml --break-system-packages", file=sys.stderr)
    sys.exit(1)

from docs_gen import config_path, log
from docs_gen.commands import sync as sync_cmd


PRESETS: dict[str, list[str]] = {
    "minimal":  ["README", "ARCHITECTURE", "GOTCHAS"],
    "standard": ["README", "ARCHITECTURE", "CONTRIBUTING", "ENVIRONMENT", "RUNBOOK", "GOTCHAS"],
    # `full` is filled in at runtime from doc-types.yaml.
}


_TYPE_PROBES = [
    ("Python",   ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"]),
    ("Node",     ["package.json"]),
    ("Rust",     ["Cargo.toml"]),
    ("Go",       ["go.mod"]),
    ("Java",     ["pom.xml", "build.gradle", "build.gradle.kts"]),
    ("Ruby",     ["Gemfile"]),
]


def detect_project(repo: Path) -> tuple[str, str]:
    """Best-effort guess at (project_type, project_name)."""
    project_type = "generic"
    for label, files in _TYPE_PROBES:
        if any((repo / f).exists() for f in files):
            project_type = label
            break

    # Name detection.
    if (repo / "pyproject.toml").is_file():
        try:
            text = (repo / "pyproject.toml").read_text(encoding="utf-8")
            for line in text.splitlines():
                line = line.strip()
                if line.startswith("name") and "=" in line:
                    value = line.split("=", 1)[1].strip().strip('"').strip("'")
                    if value:
                        return project_type, value
        except OSError:
            pass
    if (repo / "package.json").is_file():
        try:
            data = json.loads((repo / "package.json").read_text(encoding="utf-8"))
            if isinstance(data, dict) and isinstance(data.get("name"), str):
                return project_type, data["name"]
        except (OSError, json.JSONDecodeError):
            pass
    return project_type, repo.resolve().name


def _load_doc_type_specs() -> dict[str, dict]:
    """Read doc-types.yaml and return a dict keyed by doc name."""
    with open(config_path("doc-types.yaml")) as f:
        data = yaml.safe_load(f)
    return {dt["name"]: dt for dt in data["doc_types"]}


def build_doc_plan(project_name: str, preset: str, doc_types: dict[str, dict]) -> dict:
    """Build a doc-plan structure with the chosen preset."""
    if preset == "full":
        names = list(doc_types.keys())
    else:
        names = PRESETS.get(preset, PRESETS["minimal"])

    docs = []
    for name in names:
        if name not in doc_types:
            continue
        dt = doc_types[name]
        docs.append({
            "filename": dt["canonical_filename"],
            "disposition": "generate",
            "generate": True,
            "custom": False,
            "owns": [dt.get("description", "")],
            "paths": dt.get("default_paths", []) or [],
            "cadence": dt.get("default_cadence", "on-change"),
        })

    return {
        "project_name": project_name,
        "generated_at": str(date.today()),
        "docs": docs,
    }


def write_scaffolds(repo: Path, plan: dict, *, dry_run: bool = False) -> list[Path]:
    """Write empty H1-only stubs for each doc that doesn't already exist."""
    written: list[Path] = []
    for entry in plan["docs"]:
        path = repo / entry["filename"]
        if path.exists():
            continue
        title = path.stem.replace("_", " ").title()
        body = f"# {title}\n\n*(Generated by `docs-gen init`. Replace with real content.)*\n"
        if dry_run:
            log.info(f"[dry-run] would scaffold: {path}")
        else:
            path.write_text(body, encoding="utf-8")
            written.append(path)
            log.ok(f"Scaffold written: {path.name}")
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="docs-gen init",
        description="Scaffold a docs ecosystem from zero. Solo-dev friendly defaults.",
    )
    parser.add_argument("--repo", default=".",
                        help="Repository root (default: current directory)")
    parser.add_argument("--preset", default="minimal",
                        choices=["minimal", "standard", "full"],
                        help="Doc set to scaffold (default: minimal)")
    parser.add_argument("--name", default=None,
                        help="Project name (default: auto-detected from package metadata or dir name)")
    parser.add_argument("--scaffold", action="store_true",
                        help="Also write empty H1-only stubs for missing doc files")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing doc-plan.json")
    parser.add_argument("--skip-sync", action="store_true",
                        help="Just write the plan; don't run build-registry / generate-action / audit")
    parser.add_argument("--interactive", action="store_true",
                        help="Ask three quick questions instead of using detected defaults")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print intended writes without modifying the filesystem")
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        log.error(f"Repo path is not a directory: {repo}")
        return 1

    project_type, default_name = detect_project(repo)
    project_name = args.name or default_name
    preset = args.preset

    if args.interactive:
        try:
            print(f"Detected project: {project_name} ({project_type})")
            response = input(f"Project name [{project_name}]: ").strip()
            if response:
                project_name = response
            response = input(f"Preset [minimal/standard/full] [{preset}]: ").strip()
            if response in PRESETS or response == "full":
                preset = response
            response = input("Write empty stub files for missing docs? [y/N]: ").strip().lower()
            args.scaffold = response in ("y", "yes")
        except EOFError:
            log.warn("No stdin available; falling back to defaults.")

    log.info(f"Initializing docs ecosystem for {project_name} ({project_type}, {preset} preset)")

    try:
        doc_types = _load_doc_type_specs()
    except FileNotFoundError as exc:
        log.error(f"Cannot read packaged doc-types.yaml: {exc}")
        return 1
    except yaml.YAMLError as exc:
        log.error(f"doc-types.yaml is malformed: {exc}")
        return 1

    plan = build_doc_plan(project_name, preset, doc_types)
    plan_dir = repo / ".docs-meta"
    plan_path = plan_dir / "doc-plan.json"

    if plan_path.exists() and not args.force:
        log.error(f"{plan_path} already exists. Re-run with --force to overwrite.")
        return 1

    if args.dry_run:
        log.info(f"[dry-run] would write: {plan_path} with {len(plan['docs'])} doc(s)")
    else:
        plan_dir.mkdir(parents=True, exist_ok=True)
        plan_path.write_text(json.dumps(plan, indent=2) + "\n")
        log.ok(f"Wrote {plan_path}")

    if args.scaffold:
        write_scaffolds(repo, plan, dry_run=args.dry_run)

    if args.skip_sync:
        log.info("Skipping sync (--skip-sync). Run `docs-gen sync` when you're ready.")
        return 0

    sync_args = [
        str(plan_path),
        "--output-dir", str(repo),
        "--workflows-dir", str(repo / ".github" / "workflows"),
        "--audit-log", str(repo / "DOCS_AUDIT_LOG.md"),
    ]
    if args.dry_run:
        sync_args.append("--dry-run")
    return sync_cmd.main(sync_args)
